feat: expose BatchCounter for MetricBatcher
cloudfoundry/dropsonde pull request #28
Opened 2024-12-19 12:51 UTC by b1tamara

Exposing BatchCounter allows to set Tags for the metrics (similar to metric sender ValueCounter)
Related to https://github.com/cloudfoundry/routing-release/issues/445

2024-12-19 12:52 UTC, b1tamara commented
@geofffranks Could you maybe review it?

2024-12-19 15:01 UTC, Dariquest requested changes

2024-12-19 15:01 UTC, Dariquest commented on metrics/metrics.go
> +	BatchCounter(name string) metricbatcher.BatchCounterChainer
```suggestion
	BatchCounter(name string) metricBatcher.BatchCounterChainer
```

2024-12-19 15:01 UTC, Dariquest commented on metrics/metrics.go
> +	BatchCounter(name string) metricbatcher.BatchCounterChainer
the camel case is lost here, it does not correspond to the other code

2024-12-19 15:01 UTC, Dariquest commented on metrics/metrics.go
> +	"github.com/cloudfoundry/dropsonde/metricbatcher"
```suggestion
	"metricBatcher github.com/cloudfoundry/dropsonde/metricbatcher"
```

2024-12-20 07:03 UTC, b1tamara commented on metrics/metrics.go
> +	BatchCounter(name string) metricbatcher.BatchCounterChainer
as it is imported library name, I will not change it.

2025-01-09 08:25 UTC, chombium commented on metrics/metrics.go
> +	"github.com/cloudfoundry/dropsonde/metricbatcher"
I agree with @b1tamara, the imported package should not be aliased in camel case notation.

@Dariquest `Good package names are short and clear. They are lower case, with no under_scores or mixedCaps.`. Check the whole blogpost on [package names](https://go.dev/blog/package-names) for more information ;)

2025-01-15 10:19 UTC, Dariquest commented on metrics/metrics.go
> +	BatchCounter(name string) metricbatcher.BatchCounterChainer
The name is not longer and more readable in camel case, that' s why I would prefer that. It was only a suggestion, of course you are free to keep it.

2025-01-15 10:26 UTC, Dariquest commented on metrics/metrics.go
> +	"github.com/cloudfoundry/dropsonde/metricbatcher"
Thanks for the blogpost @chombium. The name is not longer and more readable in camel case. Only imho. My suggestion might be more appropriate for other programming languages then Go, which I am used to.

2025-01-15 10:34 UTC, Dariquest approved these changes

2025-01-15 21:48 UTC, chombium commented on metrics/metrics.go
> +	"github.com/cloudfoundry/dropsonde/metricbatcher"
@Dariquest I know what you mean and I would completely agree if it wasn't Go. Go has some different conventions. On the other hand, we have the same import used like here in many places in other CF components.

2025-01-16 08:13 UTC, chombium approved these changes
LGTM! 
@ctlong, @geofffranks  any objections maybe?

2025-02-05 17:00 UTC, ctlong requested changes
Changing the interface breaks some of the implementations. Most notably, the `metricbatcher.MetricBatcher` struct, as well as many generated mocks in other packages in this repo.

You can see some errors by running `golangci-lint run ./...` and/or `go test -race ./...` from the repo root.

2025-02-05 17:30 UTC, ctlong commented
As an alternative to this change, could your package instead wire up metrics on it's own? If you skip the initialize function then you can pass in a `metricsbatcher.MetricBatcher` that you've built, which already exposes a method to retrieve the `BatcherCounterChainer`.

2025-02-06 10:55 UTC, b1tamara commented
We decided to move to prometheus. I am closing the PR.

2025-02-06 10:55 UTC, closed without merging